import os
from langchain.document_loaders import (
   BSHTMLLoader,
   PyPDFLoader,
   AirbyteJSONLoader,
   ApifyDatasetLoader,
   ArxivLoader,
   AZLyricsLoader,
   AzureBlobStorageContainerLoader,
   AzureBlobStorageFileLoader,
   BigQueryLoader,
   BiliBiliLoader,
   BlackboardLoader,
   BlockchainDocumentLoader,
   ChatGPTLoader,
   CollegeConfidentialLoader,
   ConfluenceLoader,
   CoNLLULoader,
   CSVLoader,
   DataFrameLoader,
   DiffbotLoader,
   DirectoryLoader,
   DiscordChatLoader,
   Docx2txtLoader,
   DuckDBLoader,
   EverNoteLoader,
   FacebookChatLoader,
   GCSDirectoryLoader,
   GCSFileLoader,
   GitbookLoader,
   GitLoader,
   GoogleApiYoutubeLoader,
   GoogleDriveLoader,
   GutenbergLoader,
   HNLoader,
   HuggingFaceDatasetLoader,
   IFixitLoader,
   ImageCaptionLoader,
   IMSDbLoader,
   JSONLoader,
   MathpixPDFLoader,
   ModernTreasuryLoader,
   MWDumpLoader,
   NotebookLoader,
   NotionDBLoader,
   NotionDirectoryLoader,
   ObsidianLoader,
   OneDriveLoader,
   OnlinePDFLoader,
   OutlookMessageLoader,
   PDFMinerLoader,
   PDFMinerPDFasHTMLLoader,
   PlaywrightURLLoader,
   PyMuPDFLoader,
   PyPDFDirectoryLoader,
   PyPDFium2Loader,
   PythonLoader,
   ReadTheDocsLoader,
   RedditPostsLoader,
   RoamLoader,
   S3DirectoryLoader,
   S3FileLoader,
   SeleniumURLLoader,
   SitemapLoader,
   SlackDirectoryLoader,
   SpreedlyLoader,
   SRTLoader,
   StripeLoader,
   TelegramChatLoader,
   TextLoader,
   TomlLoader,
   TwitterTweetLoader,
   UnstructuredAPIFileIOLoader,
   UnstructuredAPIFileLoader,
   UnstructuredEmailLoader,
   UnstructuredEPubLoader,
   UnstructuredFileIOLoader,
   UnstructuredFileLoader,
   UnstructuredHTMLLoader,
   UnstructuredImageLoader,
   UnstructuredMarkdownLoader,
   UnstructuredODTLoader,
   UnstructuredPDFLoader,
   UnstructuredPowerPointLoader,
   UnstructuredRTFLoader,
   UnstructuredURLLoader,
   UnstructuredWordDocumentLoader,
   WebBaseLoader,
   WhatsAppChatLoader,
   WikipediaLoader,
   YoutubeLoader,
)


DOCUMENT_LOADERS = {
    'html': BSHTMLLoader,
    'pdf':  PyPDFLoader,
    'xxx':  AirbyteJSONLoader,
    'xxx':  ApifyDatasetLoader,
    'xxx':  ArxivLoader,
    'xxx':  AZLyricsLoader,
    'xxx':  AzureBlobStorageContainerLoader,
    'xxx':  AzureBlobStorageFileLoader,
    'xxx':  BigQueryLoader,
    'xxx':  BiliBiliLoader,
    'xxx':  BlackboardLoader,
    'xxx':  BlockchainDocumentLoader,
    'xxx':  ChatGPTLoader,
    'xxx':  CollegeConfidentialLoader,
    'xxx':  ConfluenceLoader,
    'xxx':  CoNLLULoader,
    'xxx':  CSVLoader,
    'xxx':  DataFrameLoader,
    'xxx':  DiffbotLoader,
    'xxx':  DirectoryLoader,
    'xxx':  DiscordChatLoader,
    'xxx':  Docx2txtLoader,
    'xxx':  DuckDBLoader,
    'xxx':  EverNoteLoader,
    'xxx':  FacebookChatLoader,
    'xxx':  GCSDirectoryLoader,
    'xxx':  GCSFileLoader,
    'xxx':  GitbookLoader,
    'xxx':  GitLoader,
    'xxx':  GoogleApiYoutubeLoader,
    'xxx':  GoogleDriveLoader,
    'xxx':  GutenbergLoader,
    'xxx':  HNLoader,
    'xxx':  HuggingFaceDatasetLoader,
    'xxx':  IFixitLoader,
    'xxx':  ImageCaptionLoader,
    'xxx':  IMSDbLoader,
    'json': JSONLoader,
    'xxx':  MathpixPDFLoader,
    'xxx':  ModernTreasuryLoader,
    'xxx':  MWDumpLoader,
    'xxx':  NotebookLoader,
    'xxx':  NotionDBLoader,
    'xxx':  NotionDirectoryLoader,
    'xxx':  ObsidianLoader,
    'xxx':  OneDriveLoader,
    'xxx':  OnlinePDFLoader,
    'xxx':  OutlookMessageLoader,
    'xxx':  PDFMinerLoader,
    'xxx':  PDFMinerPDFasHTMLLoader,
    'xxx':  PlaywrightURLLoader,
    'xxx':  PyMuPDFLoader,
    'xxx':  PyPDFDirectoryLoader,
    'xxx':  PyPDFium2Loader,
    'py':   PythonLoader,
    'xxx':  ReadTheDocsLoader,
    'xxx':  RedditPostsLoader,
    'xxx':  RoamLoader,
    'xxx':  S3DirectoryLoader,
    'xxx':  S3FileLoader,
    'xxx':  SeleniumURLLoader,
    'xxx':  SitemapLoader,
    'xxx':  SlackDirectoryLoader,
    'xxx':  SpreedlyLoader,
    'xxx':  SRTLoader,
    'xxx':  StripeLoader,
    'xxx':  TelegramChatLoader,
    'txt':  TextLoader,
    'xxx':  TomlLoader,
    'xxx':  TwitterTweetLoader,
    'xxx':  UnstructuredAPIFileIOLoader,
    'xxx':  UnstructuredAPIFileLoader,
    'xxx':  UnstructuredEmailLoader,
    'xxx':  UnstructuredEPubLoader,
    'xxx':  UnstructuredFileIOLoader,
    'xxx':  UnstructuredFileLoader,
    'xxx':  UnstructuredHTMLLoader,
    'xxx':  UnstructuredImageLoader,
    'xxx':  UnstructuredMarkdownLoader,
    'xxx':  UnstructuredODTLoader,
    'xxx':  UnstructuredPDFLoader,
    'xxx':  UnstructuredPowerPointLoader,
    'rtf':  UnstructuredRTFLoader,
    'xxx':  UnstructuredURLLoader,
    'xxx':  UnstructuredWordDocumentLoader,
    'xxx':  WebBaseLoader,
    'xxx':  WhatsAppChatLoader,
    'xxx':  WikipediaLoader,
    'xxx':  YoutubeLoader,
}

def load_document(filename):
    suffix = os.path.splitext(filename)[1][1:]  # Get the file suffix
    if suffix in DOCUMENT_LOADERS:
        return DOCUMENT_LOADERS[suffix](filename).load_and_split()
    print( f'no loader found found for {filename} ({suffix}), bro' )
    return None
